name: Enforce License Compliance

on:
  pull_request:
    branches: [main, master]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: meta-introspector/action-enforce-license-compliance@main # main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
